INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองกระบี่','Muang krabi',01);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เกาะลันตา','Ko lanta',01);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เขาพนม','Khaong phanom',01);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('คลองท่อม','Khlong thom',01);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ปลายพระยา','Plai phraya',01);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ลำทับ','Lum tub',01);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เหนือคลอง','Nua klong',01);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('อ่าวลึก','Ao Luk',01);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('คลองสาน','Klongsan',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('คลองเตย','Klongtoey',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('จอมทอง','Chomthong',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('จตุจักร','Jatujak',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ดุสิต','Dusit',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ดอนเมือง','Don muang',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ตลิ่งชัน','Taling chan',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ธนบุรี','Thon buri',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางกอกน้อย','Bangkok noi',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางกอกใหญ่','Bangkok yai',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางกะปิ','Bangkapi',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางขุนเทียน','Bangkuntien',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางเขน','Bang khen',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางคอแหลม','Bangkholam',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางซื่อ','Bangsue',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางพลัด','Bangplad',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางรัก','Bangrak',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บึงกุ่ม','Bung kum',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ประเวศ','Prawet',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ปทุมวัน','Patumwan',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ป้อมปราบศัตรูพ่าย','Pom prap',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พญาไท','Payathai',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พระโขนง','Prakanong',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พระนคร','Phranakhon',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ภาษีเจริญ','Pasricharoen',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('มีนบุรี','Minburi',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ยานนาวา','Yannawa',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ราชเทวี','Ratchathervi',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ราษฎร์บูรณะ','Radburana',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ลาดกระบัง','Lat Krabang ',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ลาดพร้าว','Lat Phrao',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สาทร','Sathorn',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สัมพันธวงศ์','Samphanthawongse',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หนองแขม','Nongkhaem',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หนองจอก','Nong chokn',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ห้วยขวาง','Huai khwang',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สวนหลวง','Suanluang',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ดินแดง','Dindaeng',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หลักสี่','Laksi',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สายไหม','Saimai',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('คันนายาว','Kannayao',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สะพานสูง','Saphansung',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('วังทองหลาง','Wang thonglang',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('คลองสามวา','Klongsamwa',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('วัฒนา','Watthana',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางนา','Bangna',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ทวีวัฒนา','Thawiwatthana',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางแค','Bangkhae',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ทุ่งครุ','Thung khru',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางบอน','Bangbon',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองกาญจนบุรี','Muang kanchanaburi',03);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ด่านมะขามเตี้ย','Dan makham tia',03);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ทองผาภูมิ','Thong pha phum',03);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ท่าม่วง','Tha muang',03);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ท่ามะกา','Tha maka',03);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ไทรโยค','Sai yok',03);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ่อพลอย','Bo phloi',03);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พนมทวน','Phanom thoan',03);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เลาขวัญ','Lao khwan',03);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ศรีสวัสดิ์','Si sawat',03);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สังขละบุรี','Sangkhla buri',03);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หนองปรือ','Nongprue',03);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ห้วยกระเจา','Huai krajao',03);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองกาฬสินธุ์','Muang Kalasin',04);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('กมลาไสย','Kamalasai',04);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('กุฉินารายณ์','Kuchinarat',04);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เขาวง','Khao wong',04);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('คำม่วง','Kham muang',04);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ท่าคันโท','Tha khantho',04);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('นามน','Na mon',04);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ยางตลาด','Yang talad',04);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ร่องคำ','Rong kham',04);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สมเด็จ','Somdet',04);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สหัสขันธ์','Sahasakan',04);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หนองกุงศรี','Nong kung srin',04);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ห้วยผึ้ง','Huai phung',04);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ห้วยเม็ก','Huai mek',04);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('นาคู','Na ku',04);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สามชัย','Sam chai',04);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ดอนจาน','Don jan',04);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ฆ้องชัย','Khong chai',04);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองกำแพงเพชร','Muang kamphaeng phet',05);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ขาณุวรลักษบุรี','Khanu waralaksaburi',05);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('คลองขลุง','Khlong khlung',05);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('คลองลาน','Khlong lan',05);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ทรายทองวัฒนา','Saithong wattana',05);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ไทรงาม','Sai ngam',05);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ปางศิลาทอง','Pang silathong',05);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พรานกระต่าย','Phran kratai',05);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('อ่าวลึก','Ao Luk',01);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บึงสามัคคี','',05);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โกสัมพีนคร','',05);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองขอนแก่น','Muang khonkean',06);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('กระนวน','kranuan',06);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เขาสวนกวาง','Khao suan kwang',06);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โคกโพธิ์ไชย','Khok pho chai',06);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ชำสูง','Some sung',06);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ชนบท','Chonnabot',06);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ชุมแพ','Chum phae',06);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('น้ำพอง','Nam phong',06);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านไผ่','Ban phai',06);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านฝาง','Ban fang',06);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เปือยน้อย','Puai noi',06);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พล','Phon',06);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พระยืน','Phra yun',06);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ภูเวียง','Phu wiang',06);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ภูผาม่าน','Phu pha man',06);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('มัญจาคีรี','Mancha khiri',06);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แวงน้อย','Wang noi',06);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แวงใหญ่','Wang yai',06);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สีชมพู','Si chomphu',06);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หนองสองห้อง','Nong song hong',06);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หนองเรือ','Nong rua',06);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หนองนาคำ','Nong na kham',06);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('อุบลรัตน์','Ubol rat',06);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โนนศิลา','Non sila',06);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านแฮด','Ban haak',06);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองจันทบุรี','Muang chanthaburi',07);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แก่งหางแมว','Kaeng hang maeo',07);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ขลุง','Khlung',07);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ท่าใหม่','Tha mai',07);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('นายายอาม','Na yai am',07);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โป่งน้ำร้อน','Pong nam ron',07);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('มะขาม','Makham',07);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สอยดาว','Soi dao',07);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แหลมสิงห์','Laem sing',07);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เขาคิชฌกูฏ','',07);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองฉะเชิงเทรา','Muang Chachoengsao',08);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางคล้า','Bang khla',08);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางน้ำเปรี้ยว','Bang nam prieo',08);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางปะกง','Bangprakong',08);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านโพธิ์','Ban pho',08);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แปลงยาว','Piaeng yao',08);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พนมสารคาม','Phanom sarakham',08);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ราชสาส์น','Ratchasan',08);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สนามชัยเขต','Sanam chai khet',08);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ท่าตะเกียบ','Tha takep',08);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('คลองเขื่อน','',08);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองชลบุรี','Muang chon buri',09);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เกาะสีชัง','Ko sichang',09);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ่อทอง','Bo thong',09);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางละมุง','Bang lamung',09);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านบึง','Ban bung',09);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พานทอง','Phan thong',09);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พนัสนิคม','Phanat nikhom',09);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ศรีราชา','Siracha',09);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สัตหีบ','Sattahip',09);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หนองใหญ่','Nong Yai',09);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เกาะจันทร์','Ko chan',09);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองชัยนาท','Muang chai nat',10);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('มโนรมย์','Manorom',10);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('วัดสิงห์','Wat singh',10);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สรรคบุรี','Sankhaburi',10);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สรรพยา','Sappraya',10);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หันคา','Hankha',10);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หนองมะโมง','Nongmanong',10);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เนินขาม','Noen kham',10);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองชัยภูมิ','Muang chai yaphum',11);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เกษตรสมบูรณ์','Kaset sombun',11);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แก้งคร้อ','Kaeng khro',11);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('คอนสวรรค์','Khon sawan',11);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('คอนสาร','Khon san',11);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('จัตุรัส','Chatturat',11);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เทพสถิต','Thep sathit',11);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เนินสง่า','Noen sanga',11);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านเขว้า','Ban klwao',11);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านแท่น','Ban thaen',11);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บำเหน็จณรงค์','Bamnet narong',11);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ภูเขียว','Phu khieo',11);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ภักดีชุมพล','Phakdi chum phon',11);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หนองบัวแดง','Nong bua daeng',11);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หนองบัวระเหว','Nong bua rawe',11);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ซับใหญ่','Sap yai',11);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองชุมพร','Muang chum phon',12);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ท่าแซะ','tha sae',12);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ทุ่งตะโก','Thung tako',12);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ปะทิว','Pathiu',12);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พะโต๊ะ','Phato',12);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ละแม','Lamae',12);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สวี','Sawi',12);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หลังสวน','Lang suan',12);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองเชียงราย','Muang chiang rai',13);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ขุนตาล','Khun tan',13);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เชียงของ','Chiang khong',13);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เชียงแสน','Chiang saen',13);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เทิง','Thoeng',13);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ป่าแดด','Pa daet',13);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พาน','Phan',13);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แม่จัน','Mae chan',13);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางกอกใหญ่','Bangkok yai',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แม่สรวย','Mae suai',13);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แม่สาย','Mae sai',13);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เวียงแก่น','Wiang Kaen',13);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เวียงชัย','Wiang chai',13);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เวียงป่าเป้า','Wiang pa pao',13);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พญาเม็งราย','Phaya mengrai',13);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แม่ลาว','Mae lao',13);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ดอยหลวง','Doi Luang',13);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เวียงเชียงรุ้ง','Wiang chiang rung',13);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองเชียงใหม่','Muang chiang mai',14);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('จอมทอง','chom thaon',14);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เชียงดาว','Chiang dao',14);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ไชยปราการ','Chai prakan',14);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ดอยเต่า','Doi tao',14);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ดอยหล่อ','Doi lo',14);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ดอยสะเก็ด','Doi saket',14);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ฝาง','Fang',14);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พร้าว','Phrao',14);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แม่แจ่ม','Mae chaem',14);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แม่แตง','Mae taeng',14);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แม่ริม','Mae rim',14);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แม่วาง','Mae wang',14);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แม่อาย','Mae ai',14);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แม่ออน','Mae on',14);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เวียงแหง','Wiang haeng',14);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สะเมิง','Samoeng',14);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สันกำแพง','Sankamphaeng',14);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สันทราย','San sai',14);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สันป่าตอง','San pa tong',14);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สารภี','Saraphi',14);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หางดง','Hang dong',14);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('อมก๋อย','Omkoi',14);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ฮอด','Hot',14);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองตรัง','Muang trang',15);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('กันตัง','Kantang',15);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ปะเหลียน','Palian',15);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ย่านตาขาว','Yan ta khao',15);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('รัษฎา','Ratsada',15);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สิเกา','Sikao',15);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ห้วยยอด','Huai Yot',15);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('วังวิเศษ','Wang wiset',15);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หาดสำราญ','Had someran',15);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('นาโยง','Na yong',15);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองตราด','Muang trat',16);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เกาะช้าง','Chang island',16);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เขาสมิง','Khao saming',16);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('คลองใหญ่','Khlong yai',16);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ่อไร่','Bo rai',16);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แหลมงอบ','Laem ngob',16);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เกาะกูด','Kut island',16);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองตาก','Muang tak',17);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ท่าสองยาง','Tha song yang',17);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านตาก','Ban Tak',17);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พบพระ','Prop phra',17);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แม่ระมาด','Mae ramat',17);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แม่สอด','Mae sot',17);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สามเงา','Sam ngao',17);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('อุ้มผาง','Um phang',17);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('วังเจ้า','Wang jao',17);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองนครนายก','Muang nakhon nayok',18);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านนา','Ban na',18);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ปากพลี','Pak phli',18);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('องครักษ์','Ongkharak',18);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองนครปฐม','Muang nakhon pathom',19);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('กำแพงแสน','Kampheng saen',19);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ดอนตูม','Don tom',19);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('นครชัยศรี','INakhon chaisi',19);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางเลน','Bang len',19);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พุทธมณฑล','Bukkha monthon',19);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สามพราน','Sam phran',19);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองนครพนม','Muang nakhon phanom',20);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ท่าอุเทน','Tha uthen',20);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ธาตุพนม','That phanom',20);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('นาแก','Na kae',20);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('นาหว้า','Na wa',20);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านแพง','Ban phaeng',20);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ปลาปาก','Pla pak',20);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โพนสวรรค์','Phon sawan',20);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เรณูนคร','Ranu nakhon',20);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ศรีสงคราม','Si songkhram',20);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('วังยาง','Wong yang',20);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('นาทม','Na thom',20);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองนครราชสีมา','Muang nakhon ratchasima',21);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แก้งสนามนาง','Kaeng snam nang',21);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ขามทะเลสอ','Kham thaie so',21);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ขามสะแกแสง','Kham sakae saeng',21);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('คง','Khong',21);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ครบุรี','Khon buri',21);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('จักราช','Chakarat',21);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ชุมพวง','Chum phuang',21);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โชคชัย','Chok chai',21);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ด่านขุนทด','Dan khunthot',21);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โนนแดง','Non daeng',21);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โนนไทย','Non thai',21);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โนนสูง','Non sung',21);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บัวใหญ่','Bua yai',21);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านเหลื่อม','Ban luarm',21);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ประทาย','Pra thai',21);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ปักธงชัย','Pak thong chai',21);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ปทุมวัน','Patumwan',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พิมาย','Phimai',21);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('วังน้ำเขียว','Wong namkhieo',21);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สีคิ้ว','Sikhui',21);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สูงเนิน','Sung noe',21);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เสิงสาง','Soeng sang',21);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ห้วยแถลง','Huai thalaeng',21);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หนองบุนนาก','Nong bunnak',21);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เทพารักษ์','Tepharak',21);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองยาง','Muang yang',21);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พระทองคำ','Phra thorngkham',21);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ลำทะเมนชัย','Lum thamen chai',21);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เฉลิมพระเกียรติ','Chaloem phrakiat ',21);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สีดา','Sida',21);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บัวลาย','Bua lai',21);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองนครศรีธรรมราช','Muang nakhon si thammarat',22);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ขนอม','Khanom',22);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ฉวาง','Chawang',22);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ชะอวด','Cha-uat',22);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เชียรใหญ่','Chian yai',22);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ท่าศาลา','Tha sala',22);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ทุ่งใหญ่','Thung yai',22);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ทุ่งสง','Thung song',22);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พระพรหม','Phra phrom',22);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('นาบอน','Na bon',22);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางขัน','Bang chan',22);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ปากพนัง','Pak phanang',22);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พรหมคีรี','Phrommakhiri',22);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พิปูน','Phipun',22);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ร่อนพิบูลย์','Ron pipun',22);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ลานสะกา','Lan saka',22);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สิชล','Sichon',22);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หัวไทร','Hua sai',22);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('จุฬาภรณ์','Chulaporn',22);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('นบพิตำ','Nop pitam',22);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ช้างกลาง','Chang klang',22);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ถ้ำพรรณรา','Tham phanara',22);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เฉลิมพระเกียรติ','Chaloem phrakiat ',22);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองนครสวรรค์','Muang nakhon sawan',23);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เก้าเลี้ยว','Kao lieo',23);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โกรกพระ','Krok phra',23);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ชุมแสง','Chumsaeng',23);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ตากฟ้า','Tak fa',23);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ตาคลี','Takeli',23);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ท่าตะโก','Tha tako',23);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บรรพตพิสัย','Banphot phisai',23);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พยุหคีรี','Phayuha khiri',23);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ไพศาลี','Phai Sali',23);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แม่วงก์','Mae wong',23);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ลาดยาว','Lao yao',23);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หนองบัว','Nong bua',23);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แม่เปิน','',23);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ชุมตาบง','Chum ta bong',23);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองนนทบุรี','Muang nonthaburi',24);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ไทรน้อย','Sai noi',24);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางกรวย','Bang kruai',24);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางบัวทอง','Bang bua thong',24);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางใหญ่','Bang yai',24);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ปากเกร็ด','Pakkred',24);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองนราธิวาส','Muang narathiwat',25);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('จะแนะ','Chanao',25);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ตากใบ','Tak bai',25);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บาเจาะ','Bacho',25);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ยี่งอ','Yi-ngo',25);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ระแงะ','Rangae',25);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('รือเสาะ','Ruso',25);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แว้ง','Waeng',25);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ศรีสาคร','Sisakhon',25);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สุคิริน','Sukhirin',25);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สุไหงโกลก','Sungai kolok',25);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สุไหงปาดี','Sungai padi',25);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เจาะไอร้อง','',25);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองน่าน','Muang nan',26);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เชียงกลาง','Cheang klang',26);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ท่าวังผา','Tha wang pha',26);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ทุ่งช้าง','Thung chang',26);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('นาน้อย','na noi',26);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('นาหมื่น','Na mun',26);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านหลวง','Ban luang',26);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ปัว','Pua',26);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แม่จริม','Mae chrim',26);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เวียงสา','Wiang sa',26);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สันติสุข','Suntisuk',26);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ่อเกลือ','Bo kluai',26);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สองแคว','Song kwar',26);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เฉลิมพระเกียรติ','Chaloem phrakiat ',26);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ภูเพียง','Phu pieng',26);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองบุรีรัมย์','Muang buri ram',27);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('กระสัง','Krasang',27);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('คูเมือง','Khu Muang',27);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ชำนิ','Cham ni',27);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('นาโพธิ์','Na pho',27);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('นางรอง','Nang rong',27);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โนนดินแดง','Non din daeng',27);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โนนสุวรรณ','Non suwan',27);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านกรวด','Ban kruat',27);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พลับพลาชัย','Phlapphachai',27);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านใหม่ไชยพจน์','Ban mai chaiyapot',27);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ประโคนชัย','Phakhon chai',27);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ปะคำ','Pa kham',27);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ลาดกระบัง','Lat Krabang ',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ละหานทราย','Lahan sai',27);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ลำปลายมาศ','Lam plai mat',27);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สตึก','Satuk',27);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หนองกี่','Nong ki',27);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หนองหงส์','Nong hong',27);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ห้วยราช','Huai rat',27);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านด่าน','Ban dan',27);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เฉลิมพระเกียรติ','Chaloem phrakiat ',27);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แคนดง','Can dong',27);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองปทุมธานี','Mung pathum thani',28);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('คลองหลวง','Klongluang',28);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ธัญบุรี','Thanyaburi',28);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ลาดหลุมแก้ว','Lat lum kaeo',28);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ลำลูกกา','Lam luk ka',28);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สามโคก','Sam khok',28);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หนองเสือ','Nong sua',28);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองประจวบคีรีขันธ์','Mung prachuap khiri khan',29);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('กุยบุรี','Kui buri',29);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ทับสะแก','Thap sakae',29);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางสะพาน','Bang saphan',29);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางสะพานน้อย','Bang saphan noi',29);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ปราณบุรี','Pran buri',29);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หัวหิน','Hua hin',29);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สามร้อยยอด','Sam roi yot',29);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองปราจีนบุรี','Muang prachinburi',30);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('กบินทร์บุรี','Kabin buri',30);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ศรีมโหสถ','Sri maho sot',30);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('นาดี','Nadi',30);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านสร้าง','Ban Sang',30);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ประจันตคาม','Prachantakham',30);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ศรีมหาโพธิ','Si maha phot',30);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองปัตตานี','Muang pattani',31);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('กะพ้อ','Kapho',31);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โคกโพธิ์','Khok pho',31);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ทุ่งยางแดง','Thung yang daeng',31);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ปะนาเระ','Panara',31);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('มายอ','Mayo',31);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ไม้แก่น','Mai kaen',31);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ยะรัง','Yarang',31);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ยะหริ่ง','Yaring',31);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สายบุรี','Sai buri',31);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หนองจิก','Nong chik',31);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แม่ลาน','Mae lan',31);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พระนครศรีอยุธยา','Phranakhon si ayutthaya ',32);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ท่าเรือ','Tha rua',32);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('นครหลวง','Nakhon luang',32);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางซ้าย','Bang sai',32);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางไทร','Bang sai',32);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางบาล','Bang ban',32);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางปะหัน','Bang pahan',32);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางปะอิน','Bang pa-in',32);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านแพรก','Ban phraek',32);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ผักไห่','Phak hai',32);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ภาชี','Phachi',32);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('มหาราช','Maharat',32);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ลาดบัวหลวง','Lat bua luang',32);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('วังน้อย','Wang noi',32);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เสนา','Sena',32);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('อุทัย','Uthai',32);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองพะเยา','Muang Phayao',33);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('จุน','Chun',33);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เชียงคำ','Chiang kham',33);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เชียงม่วน','Chiang muan',33);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ดอกคำใต้','Dok kham tai',33);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ปง','Pong',33);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แม่ใจ','Mae chai',33);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ภูซาง','Phu sang',33);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ภูกามยาว','Phu kam yao',33);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองพังงา','Muang phangnga',34);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('กะปง','ka pong',34);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เกาะยาว','ko yao',34);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('คุระบุรี','Khura buri',34);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ตะกั่วทุ่ง','Takua thung',34);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ตะกั่วป่า','Takua pa',34);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ทับปุด','Thap put',34);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ท้ายเหมือง','Thai muang',34);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองพัทลุง','Muang phatthalung',35);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('กงหรา','kong ra',35);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เขาชัยสน','Khao chaison',35);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ควนขนุน','Khuan khanon',35);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ตะโหมด','Tamot',35);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ปากพะยูน','Pak phayun',35);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ป่าบอน','Pa bon',35);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ป่าพะยอม','Pa phayom',35);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ศรีบรรพต','Si banphot',35);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางแก้ว','Bang kaeo',35);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ศรีนครินทร์','',35);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองพิจิตร','Muang phichit',36);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ตะพานหิน','Taphan hin',36);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ทับคล้อ','Thao khlo',36);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางมูลนาก','Bang munnak',36);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โพทะเล','Pho thale',36);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โพธิ์ประทับช้าง','',36);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สามง่าม','Sam ngam',36);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('วังทรายพูน','Wang sai phun',36);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สากเหล็ก','Sak lek',36);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บึงนาราง','Bung narang',36);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ดงเจริญ','Dong charoen',36);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('วชิรบารมี','',36);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สายไหม','Saimai',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('นครไทย','Nakhon thai',37);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ชาติตระการ','Chat trakan',37);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เนินมะปราง','Noen maprang',37);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางกระทุ่ม','Bangkrathum',37);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางระกำ','Bangrakam',37);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พรหมพิราม','Phrom phiram',37);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('วังทอง','Wang thong',37);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('วัดโบสถ์','Wat bot',37);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองเพชรบุรี','muang phetchaburi',38);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แก่งกระจาน','Kaeng kachan',38);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เขาย้อย','khao yoi',38);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ชะอำ','Cha-am',38);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ท่ายาง','Tha yang',38);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านลาด','Ban lat',38);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านแหลม','Ban laerm',38);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หนองหญ้าปล้อง','Nong ya plong',38);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองเพชรบูรณ์','Muang phetchabun',39);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เขาค้อ','Khao Kho',39);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ชนแดน','Chon daen',39);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('น้ำหนาว','Nam nao',39);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บึงสามพัน','Bung sam phan',39);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('วิเชียรบุรี','Wichian buri',39);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ศรีเทพ','Si thep',39);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หนองไผ่','Nong Phai',39);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หล่มเก่า','Lom kao',39);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หล่มสัก','Lom sak',39);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('วังโป่ง','Wang pong',39);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองแพร่','Muangphrae',40);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เด่นชัย','Den chai',40);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ร้องกวาง','Rong kwang',40);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ลอง','Long',40);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('วังชิ้น','Wang chin',40);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สอง','Song',40);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หนองม่วงไข่','Nong muang kai',40);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สูงเม่น','Sung men',40);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองภูเก็ต','Muangphuket',41);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('กะทู้','Kathu',41);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ถลาง','Thalang',41);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองมหาสารคาม','Muang mahasarakham',42);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('กันทรวิชัย','Kantharawichai',42);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แกดำ','Kae dam',42);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โกสุมพิสัย','Kosum phisai',42);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เชียงยืน','Chiang yun',42);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('นาเชือก','Na chuak',42);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('นาดูน','Na dun',42);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บรบือ','Borabu',42);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พยัคฆภูมิพิสัย','Phayakhaphum phisai',42);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('วาปีปทุม','Wapi pathum',42);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('กุดรัง','Kut rang',42);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ยางสีสุราช','Yang si surat',42);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ชื่นชม','Chuenchom',42);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองมุกดาหาร','Muang mukdahan',43);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('คำชะอี','Khamcha-i',43);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ดงหลวง','Dong luang',43);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ดอนตาล','Don tan',43);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('นิคมคำสร้อย','Nikhom kham soi',43);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หนองสูง','Nong sung',43);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หว้านใหญ่','Wan yai',43);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองแม่ฮ่องสอน','Muang mae hong son',44);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ขุนยวม','Khun yuam',44);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ปางมะผ้า','Pang mapha',44);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ปาย','Pai',44);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แม่ลาน้อย','Mae la noi',44);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แม่สะเรียง','Mae sariang',44);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สบเมย','Sop moei',44);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองยโสธร','Muang yasothon',45);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('กุดชุม','Kut chum',45);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ค้อวัง','Kho wang',45);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('คำเขื่อนแก้ว','Kham khuan kaeo',45);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ไทยเจริญ','Thai charoen',45);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ทรายมูล','Sai mun',45);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ป่าติ้ว','Pa tiu',45);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('มหาชนะชัย','Maha chana chai',45);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เลิงนกทา','Loeng nok tha',45);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองยะลา','Muang yala',46);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('กาบัง','Kabang',46);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('กรงปินัง','',46);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ธารโต','Than to',46);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บันนังสตา','Bannang sata',46);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เบตง','Betong',46);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ยะหา','Yaha',46);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('รามัน','Raman',46);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองร้อยเอ็ด','Muang roi et',47);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เกษตรวิสัย','Kaset visai',47);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('จตุรพักตร์พิมาน','Chaturaphak phiman',47);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('จังหาร','Jung han',47);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ธวัชบุรี','Thawatshaburi',47);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ปทุมรัตน์','Pathum rat',47);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พนมไพร','Phanom phrai',47);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โพธิ์ชัย','IPho chai',47);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โพนทราย','Phon sai',47);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โพนทอง','Phon thong',47);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมยวดี','Moeiwadi',47);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองสรวง','Muangsuang',47);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ศรีสมเด็จ','Srisomdet',47);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เสลภูมิ','Sela phum',47);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สุวรรณภูมิ','Suwannaphum',47);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หนองพอก','Nong phok',47);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('อาจสามารถ','At samat',47);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางบอน','Bangbon',02);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หนองฮี','Nong hi',47);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ทุ่งเขาหลวง','Thung kao luang',47);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองระนอง','Muang ranong',48);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('กระบุรี','Kra buri',48);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('กะเปอร์','Kapoe',48);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ละอุ่น','La-un',48);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สุขสำราญ','Sook samran',48);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองระยอง','Muang rayong',49);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แกลง','Klaeng',49);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านค่าย','Ban khai',49);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านฉาง','Ban chang',49);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ปลวกแดง','Pluak daeng',49);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('วังจันทร์','Wang chan',49);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เขาชะเมา','khao chamao',49);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('นิคมพัฒนา','Nikhom phathana',49);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองราชบุรี','Muang rachaburi',50);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('จอมบึง','Chom bung',50);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ดำเนินสะดวก','Damnoen saduak',50);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางแพ','Bang phae',50);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านโป่ง','Bang phong',50);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ปากท่อ','Pak tho',50);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โพธาราม','Photharam',50);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('วัดเพลง','Wat phleng',50);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สวนผึ้ง','Suan phung',50);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านคา','Bang kha',50);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองลพบุรี','Muang lopburi',51);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โคกเจริญ','Khok charoen',51);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โคกสำโรง','Khok samrong',51);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ชัยบาดาล','Chai badan',51);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ท่าวุ้ง','Tha wong',51);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ท่าหลวง','Tha luang',51);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านหมี่','Ban mi',51);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พัฒนานิคม','Phatthana nikhom',51);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ลำสนธิ','',51);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สระโบถส์','',51);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หนองม่วง','Nong muang kai',51);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองเลย','Muang loei',52);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เชียงคาน','Chiang khan',52);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ด่านซ้าย','Dan sai',52);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ท่าลี่','Tha li',52);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('นาด้วง','Na duang',52);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('นาแห้ว','Na haeo',52);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ปากชม','Pak chom',52);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ผาขาว','',52);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ภูกระดึง','Phu kadung',52);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ภูเรือ','Phu rua',52);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ภูหลวง','Phu luang',52);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('วังสะพุง','Wang saphung',52);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เอราวัณ','Erawan',52);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หนองหิน','Nong hin',52);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองลำปาง','Muang lampang',53);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เกาะคา','Ko kha',53);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('งาว','Nhao',53);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แจ้ห่ม','Chae hom',53);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เถิน','Thoen',53);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แม่ทะ','Mea tha',53);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แม่พริก','Mea phrik',53);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองปาน','Muang pan',53);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แม่เมาะ','Mea mo',53);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('วังเหนือ','Wang nua',53);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สบปราบ','Sop prap',53);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เสริมงาม','Some ngam',53);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ห้างฉัตร','',53);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองลำพูน','Muang lamphun',54);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ทุ่งหัวช้าง','Thung hua chang',54);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านโฮ่ง','Ban hong',54);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ป่าซาง','Pa sang',54);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แม่ทา','Mea ta',54);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ลี้','Li',54);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านธิ','Ban thi',54);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เวียงหนองล่อง','',54);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองศีรสะเกษ','Muang srisaket',55);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('กันทรลักษ์','Kantharalak',55);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('กันทรารมย์','Kanthararom',55);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ขุขันธ์','Khokhon',55);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ขุนหาญ','Khun han',55);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('น้ำเกลี้ยง','Nam kliang',55);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โนนคูณ','Non khan',55);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บึงบูรพ์','Bang bun',55);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เบญจลักษณ์','Benjalak',55);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ปรางค์กู่','Prang ku',55);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พยุห์','Phayu',55);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ไพรบึง','Phai bung',55);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โพธิ์ศรีสุวรรณ','Pho si suwan',55);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ภูสิงห์','Phu sing',55);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองจันทร์','Muang chan',55);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ยางชุมน้อย','Yang chumnoi',55);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ราษีไศล','Rasi sala',55);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('วังหิน','Wang hin',55);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ศรีรัตนะ','Sirattana',55);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ห้วยทับทัน','Huai thap than',55);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('อุทุมพรพิสัย','Uthum phon phisai',55);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ศิลาลาด','Silalat',55);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองสกลนคร','Muang sakonnakhon',56);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('กุดบาก','Kot bak',56);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('กุสุมาลย์','Kusuman',56);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('คำตากล้า','Kham ta kla',56);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เจริญศิลป์','Charoen silp',56);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เต่างอย','Tao ngoi',56);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ศรีสวัสดิ์','Si sawat',03);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านม่วง','Ban muang',56);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พรรณานิคม','Phanna nikhom',56);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พังโคน','Phang khon',56);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('วานรนิวาส','Wanon niwat',56);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('วาริชภูมิ','Warit chaphum',56);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โคกศรีสุพรรณ','Khok si suphan',56);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สว่างแดนดิน','Sawang daen din',56);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ส่องดาว','Song dao',56);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('อากาศอำนวย','',56);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ภูพาน','Phu phan',56);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โพนนาแก้ว','Phon na kaeo',56);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองสงขลา','Muang songkhla',57);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('กระแสสินธุ์','Kasae sin',57);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ควนเนียง','Khuan niang',57);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('จะนะ','Chana',57);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เทพา','The pha',57);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('นาทวี','Na thawi',57);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('นาหม่อม','Na mom',57);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางกล่ำ','Bang khum',57);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ระโนด','Ranot',57);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('รัตภูมิ','Rattaphom',57);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สทิงพระ','Sathing phra',57);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สะเดา','Sadao',57);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สะบ้าย้อย','Saba yoi',57);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สิงหนคร','Singha nakhon',57);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หาดใหญ่','Hat yai',57);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('คลองหอยโข่ง','',57);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองสตูล','Muang satun',58);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ควนกาหลง','Khuan ka long',58);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ควนโดน','Khuan don',58);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ท่าแพ','Tha phae',58);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ทุ่งหว้า','Thung wa',58);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ละงู','Langu',58);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('มะนัง','Manang',58);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองสมุทรปราการ','Muang samutprakan',59);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางบ่อ','Bang bo',59);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางพลี','Bang phle',59);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พระประแดง','Phra pradaeng',59);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พระสมุทรเจดีย์','Phra samutjede',59);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางเสาธง','Bang sao thong',59);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองสมุทรสงคราม','Muang samut songkhram',60);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางคณที','',60);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('อัมพวา','',60);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองสมุทรสาคร','Muang samut sakhon',61);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('กระทุ่มแบน','Kratumban',61);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านแพ้ว','Ban phaeo',61);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองสระแก้ว','Muang sra kaeo',62);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เขาฉกรรจ์','',62);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('คลองหาด','Khlong hat',62);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ตาพระยา','Ta phraya',62);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('วังน้ำเย็น','Wang namyen',62);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('วัฒนานคร','Wattana nakhon',62);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('อรัญประเทศ','Aranyaprathat',62);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โคกสูง','Khok sung',62);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('วังสมบูรณ์','Wang somboon',62);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองสระบุรี','Muang saraburi',63);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แก่งคอย','Kaeng khoy',63);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ดอนพุด','Don phut',63);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านหมอ','Ban mo',63);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พระพุทธบาท','Phra phutthabat',63);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('มวกเหล็ก','Muak lek',63);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('วิหารแดง','Wihan daeng',63);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เสาไห้','',63);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หนองแค','Nong khae',63);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หนองแซง','Nong saeng',63);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หนองโดน','Nong don',63);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('วังม่วง','Wang muang',63);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เฉลิมพระเกียรติ','Chalermprakiat',63);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองสิงห์บุรี','Muang singburi',64);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ค่ายบางระจัน','Khai bang rachan',64);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ท่าช้าง','Tha chang',64);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางระจัน','Bangrachan',64);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พรหมบุรี','Phrom buri',64);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('อินทร์บุรี','In buri',64);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองสุโขทัย','Muang sukhothai',65);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('กงไกรลาศ','Kong kralilat',65);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('คีรีมาศ','Khiri mat',65);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ทุ่งเสลี่ยม','Thung saliam',65);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านด่านลานหอย','Ban dan lan hoi',65);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ศรีนคร','Si nakhon',65);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ศรีสัชนาลัย','Satchanalai',65);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ศรีสำโรง','Si samrong',65);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สวรรคโลก','Sawan khalok',65);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองสุพรรณบุรี','Muang suphanburi',66);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ดอนเจดีย์','Don chedi',66);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ด่านช้าง','Dan chang',66);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เดิมบางนางบวช','Doembang nangbuat',66);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บางปลาม้า','Bang plama',66);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ศรีประจันต์','Si prachan',66);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สองพี่น้อง','Song phi nong',66);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สามชุก','Sam chuk',66);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('อู่ทอง','U thong',66);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หนองหญ้าไซ','Nong yasai',66);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองสุราษฎร์ธานี','Muang surat thani',67);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('กาญจนดิษฐ์','Kanchanadit',67);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เกาะพะงัน','ko phangan',67);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เกาะสมุย','Ko samut',67);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('คีรีรัฐนิคม','Khiri ratthanikhem',67);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เคียนซา','Khian sa',67);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('นามน','Na mon',04);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ไชยา','Chai ya',67);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ดอนสัก','Don sak',67);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ท่าฉาง','Tha chang',67);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ท่าชนะ','Tha chana',67);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านตาขุน','Ban ta khun',67);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านนาเดิม','Ban na doem',67);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านนาสาร','Ban na san',67);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พนม','Phanom',67);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พระแสง','Phrasaeng',67);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พุนพิน','Phunphin',67);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('วิภาวดี','',67);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เวียงสระ','Weang sa',67);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองสุรินทร์','Muang surin',68);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('กาบเชิง','Kap choeng',68);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('จอมพระ','Chom phra',68);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ชุมพลบุรี','Chumphon buri',68);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ท่าตูม','Tha tum',68);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บัวเชด','',68);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ปราสาท','Pra sat',68);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('รัตนบุรี','Rattana buri',68);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ลำดวน','Lam duon',68);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ศีขรภูมิ','Sikhoraphum',68);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สนม','sanom',68);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สังขะ','Sang kha',68);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สำโรงทาบ','Samrong thap',68);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ศรีณรงค์','Sri narong',68);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พนมดงรัก','Phanom dong rak',68);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เขวาสินรินทร์','',68);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โนนนารายณ์','Nhon narai',68);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองหนองคาย','Muang nongkhai',69);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เซกา','Seka',69);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โซ่พิสัย','So phisai',69);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ท่าบ่อ','Tha bo',69); 
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พรเจริญ','Porncharoen',69);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โพนพิสัย','Phon phisai',69);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ศรีเชียงใหม่','Si chiang mai',69);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ศรีวิไล','Si wilai',69);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สังคม','Sang kom',69);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สระใคร่','',69); 
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('รัตนวาปี','Ratana wapi',69);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เฝ้าไร่','',69);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โพธิ์ตาก','Pho tak',69);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองหนองบัวลำภู','Muang nongbualamphu',70);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('นากลาง','Na klang',70);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โนนสัง','Non sang',70);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ศรีบุญเรือง','Si bun ruang',70);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สุวรรณคูหา','Suwannakhuha',70);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('นาวัง','Na wang',70);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองอ่างทอง','Muang angthong',71);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ไชโย','Chai yo',71);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ป่าโมก','Pamok',71);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โพธิ์ทอง','Po thong',71);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('วิเศษชัยชาญ','Wiset chai chan',71);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สามโก้','Sam ko',71);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('แสวงหา','Sawaengha',71);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองอำนาจเจริญ','Muang amnatcharoen',72);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ชานุมาน','Chanu man',72);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ปทุมราชวงศา','Pathum rachawongsa',72);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พนา','Phana',72);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เสนางคนิคม','Senangkhanikhom',72);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หัวตะพาน','Hua taphan',72);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ลืออำนาจ','Lu amnat',72);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองอุดรธานี','Muang udonthani',73);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('กู่แก้ว','Ku kaeo',73);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('กุดจับ','kut chap',73);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('กุมภวาปี','Kumphawapi',73);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ไชยวาน','Chai wan',73);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ทุ่งฝน','Thung fon',73);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('นายูง','Na yung',73);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('น้ำโสม','Nam som',73);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โนนสะอาด','Non sa-at',73);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านดุง','Bang dung',73);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านผือ','Ban phu',73);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พิบูลย์รักษ์','Pibunrak',73);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เพ็ญ','Phen',73);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('วังสามหมอ','Wang sam mo',73);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ศรีธาตุ','Si that',73);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สร้างคอม','Sang khom',73);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หนองวัวซอ','Nong wua so',73);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หนองหาน','Nong han',73);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หนองแสง','Nong saeng',73);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ประจักษ์ศิลปาคาม','',73);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองอุตรดิตถ์','Muang uttaradit',74);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ตรอน','Tron',74);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ทองแสนขัน','Thong saen khan',74);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ท่าปลา','Tha pla',74);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('น้ำปาด','Nam pat',74);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านโคก','Ban khok',74);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พิชัย','Phichai',74);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ฟากท่า','Pak tha',74);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ลับแล','laplae',74);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองอุทัยธานี','Muang uthaithani',75);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ทัพทัน','Thap than',75);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บ้านไร่','Ban rai',75);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ลานสัก','Lan sak',75);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ดอนจาน','Don jan',04);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หนองขาหย่าง','Nong khayang',75);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('หนองฉาง','Nong chang',75);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ห้วยคต','Huai khot',75);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เมืองอุบลราชธานี','Muang uboratchathani',76);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('กุดข้าวปุ้น','Kut khao pun',76);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เขมราฐ','Khemarat',76);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เขื่องใน','Khuang nai',76);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โขงเจียม','Khong chiam',76);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เดชอุดม','Deti udom',76);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ตระการพืชผล','Trakan phut phon',76);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ตาลสุม','Tan sum',76);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ทุ่งศรีอุดม','Thung si udom',76);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('นาจะหลวย','No chaluai',76);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('น้ำยืน','Nam yun',76);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บุณฑริก','Bun tharik',76);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พิบูลมังสาหาร','Phibun mangsahan',76);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โพธิ์ไทร','Pho sai',76);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ม่วงสามสิบ','muang samsip',76);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เหล่าเสือโก้ก','',76);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('วารินชำราบ','Warin shamrap',76);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ศรีเมืองใหม่','Si muang mai',76);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สำโรง','sam rong',76);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สิรินธร','Sirinthon',76);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('นาเยีย','',76);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('นาตาล','Natan',76);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('สว่างวีระวงศ์','Swang weerawong',76);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('น้ำขุ่น','',76);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ดอนมดแดง','Don mot daeng',76);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('พรเจริญ','Phon Charoen',77);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('โซ่พิสัย','So Phisai',77);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('เซกา','Seka',77);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ปากคาด','Pak Khat',77);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บึงโขงหลง','Bueng Khong Long',77);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('ศรีวิไล','Si Wilai',77);
INSERT INTO district(thname_district, enname_district, id_province) VALUES ('บุ่งคล้า','Bung Khla',77);

