INSERT INTO provinces( thname_province, enname_province)VALUES ('กระบี่','Krabi');
INSERT INTO provinces( thname_province, enname_province)VALUES ('กรุงเทพมหานคร','Bangkok');
INSERT INTO provinces( thname_province, enname_province)VALUES ('กาญจนบุรี','Kanchanaburi');
INSERT INTO provinces( thname_province, enname_province)VALUES ('กาฬสินธุ์','Kalasin');
INSERT INTO provinces( thname_province, enname_province)VALUES ('กำแพงเพชร','Kamphaeng phet');
INSERT INTO provinces( thname_province, enname_province)VALUES ('ขอนแก่น','Khon kean');
INSERT INTO provinces( thname_province, enname_province)VALUES ('จันทบุรี','Chanthaburi');
INSERT INTO provinces( thname_province, enname_province)VALUES ('ฉะเชิงเทรา','Chachoengsao');
INSERT INTO provinces( thname_province, enname_province)VALUES ('ชลบุรี','Chon buri');
INSERT INTO provinces( thname_province, enname_province)VALUES ('ชัยนาท','Chai nat');
INSERT INTO provinces( thname_province, enname_province)VALUES ('ชัยภูมิ','Chai yaphum');
INSERT INTO provinces( thname_province, enname_province)VALUES ('ชุมพร','Chum phon');
INSERT INTO provinces( thname_province, enname_province)VALUES ('เชียงราย','Chiang rai');
INSERT INTO provinces( thname_province, enname_province)VALUES ('เชียงใหม่','Chiang mai');
INSERT INTO provinces( thname_province, enname_province)VALUES ('ตรัง','Trang');
INSERT INTO provinces( thname_province, enname_province)VALUES ('ตราด','Trat');
INSERT INTO provinces( thname_province, enname_province)VALUES ('ตาก','Tak');
INSERT INTO provinces( thname_province, enname_province)VALUES ('นครนายก','Nakhon nayok');
INSERT INTO provinces( thname_province, enname_province)VALUES ('นครปฐม','Nakhon pathom');
INSERT INTO provinces( thname_province, enname_province)VALUES ('นครพนม','Nakhon phanom');
INSERT INTO provinces( thname_province, enname_province)VALUES ('นครราชสีมา','Nakhon ratchasima');
INSERT INTO provinces( thname_province, enname_province)VALUES ('นครศรีธรรมราช','Nakhon si thammarat');
INSERT INTO provinces( thname_province, enname_province)VALUES ('นครสวรรค์','Nakhon sawan');
INSERT INTO provinces( thname_province, enname_province)VALUES ('นนทบุรี','Nonthaburi');
INSERT INTO provinces( thname_province, enname_province)VALUES ('นราธิวาส','Narathiwat');
INSERT INTO provinces( thname_province, enname_province)VALUES ('น่าน','Nan');
INSERT INTO provinces( thname_province, enname_province)VALUES ('บุรีรัมย์','Buri ram');
INSERT INTO provinces( thname_province, enname_province)VALUES ('ปทุมธานี','Pathum thani');
INSERT INTO provinces( thname_province, enname_province)VALUES ('ประจวบคีรีขันธ์','Prachuap khiri khan');
INSERT INTO provinces( thname_province, enname_province)VALUES ('ปราจีนบุรี','Prachinburi');
INSERT INTO provinces( thname_province, enname_province)VALUES ('ปัตตานี','Pattani');
INSERT INTO provinces( thname_province, enname_province)VALUES ('พระนครศรีอยุธยา','Ayutthaya');
INSERT INTO provinces( thname_province, enname_province)VALUES ('พะเยา','Phayao');
INSERT INTO provinces( thname_province, enname_province)VALUES ('พังงา','Phangnga');
INSERT INTO provinces( thname_province, enname_province)VALUES ('พัทลุง','Phatthalung');
INSERT INTO provinces( thname_province, enname_province)VALUES ('พิจิตร','phichit');
INSERT INTO provinces( thname_province, enname_province)VALUES ('พิษณุโลก','Phitsanulok');
INSERT INTO provinces( thname_province, enname_province)VALUES ('เพชรบุรี','Phetchaburi');
INSERT INTO provinces( thname_province, enname_province)VALUES ('เพชรบูรณ์','Phetchabun');
INSERT INTO provinces( thname_province, enname_province)VALUES ('แพร่','Phrae');
INSERT INTO provinces( thname_province, enname_province)VALUES ('ภูเก็ต','Phuket');
INSERT INTO provinces( thname_province, enname_province)VALUES ('มหาสารคาม','Mahasarakham');
INSERT INTO provinces( thname_province, enname_province)VALUES ('มุกดาหาร','Mukdahan');
INSERT INTO provinces( thname_province, enname_province)VALUES ('แม่ฮ่องสอน','Mae hong son');
INSERT INTO provinces( thname_province, enname_province)VALUES ('ยโสธร','Yasothon');
INSERT INTO provinces( thname_province, enname_province)VALUES ('ยะลา','Yala');
INSERT INTO provinces( thname_province, enname_province)VALUES ('ร้อยเอ็ด','Roi et');
INSERT INTO provinces( thname_province, enname_province)VALUES ('ระนอง','Ranong');
INSERT INTO provinces( thname_province, enname_province)VALUES ('ระยอง','Rayong');
INSERT INTO provinces( thname_province, enname_province)VALUES ('ราชบุรี','Rachaburi');
INSERT INTO provinces( thname_province, enname_province)VALUES ('ลพบุรี','Lopburi');
INSERT INTO provinces( thname_province, enname_province)VALUES ('เลย','Loei');
INSERT INTO provinces( thname_province, enname_province)VALUES ('ลำปาง','Lampang');
INSERT INTO provinces( thname_province, enname_province)VALUES ('ลำพูน','Lamphun');
INSERT INTO provinces( thname_province, enname_province)VALUES ('ศีรสะเกษ','Srisaket');
INSERT INTO provinces( thname_province, enname_province)VALUES ('สกลนคร','Sakonnakhon');
INSERT INTO provinces( thname_province, enname_province)VALUES ('สงขลา','Songkhla');
INSERT INTO provinces( thname_province, enname_province)VALUES ('สตูล','Satun');
INSERT INTO provinces( thname_province, enname_province)VALUES ('สมุทรปราการ','Samutprakan');
INSERT INTO provinces( thname_province, enname_province)VALUES ('สมุทรสงคราม','Samut songkhram');
INSERT INTO provinces( thname_province, enname_province)VALUES ('สมุทรสาคร','Samut sakhon');
INSERT INTO provinces( thname_province, enname_province)VALUES ('สระแก้ว','Sra kaeo');
INSERT INTO provinces( thname_province, enname_province)VALUES ('สระบุรี','Saraburi');
INSERT INTO provinces( thname_province, enname_province)VALUES ('สิงห์บุรี','Singburi');
INSERT INTO provinces( thname_province, enname_province)VALUES ('สุโขทัย','Sukhothai');
INSERT INTO provinces( thname_province, enname_province)VALUES ('สุพรรณบุรี','Suphanburi');
INSERT INTO provinces( thname_province, enname_province)VALUES ('สุราษฎร์ธานี','Surat thani');
INSERT INTO provinces( thname_province, enname_province)VALUES ('สุรินทร์','Surin');
INSERT INTO provinces( thname_province, enname_province)VALUES ('หนองคาย','Nongkhai');
INSERT INTO provinces( thname_province, enname_province)VALUES ('หนองบัวลำภู','Nongbualamphu');
INSERT INTO provinces( thname_province, enname_province)VALUES ('อ่างทอง','Angthong');
INSERT INTO provinces( thname_province, enname_province)VALUES ('อำนาจเจริญ','Amnatcharoen');
INSERT INTO provinces( thname_province, enname_province)VALUES ('อุดรธานี','Udonthani');
INSERT INTO provinces( thname_province, enname_province)VALUES ('อุตรดิตถ์','Uttaradit');
INSERT INTO provinces( thname_province, enname_province)VALUES ('อุทัยธานี','Uthaithani');
INSERT INTO provinces( thname_province, enname_province)VALUES ('อุบลราชธานี','Uboratchathani');
INSERT INTO provinces( thname_province, enname_province)VALUES ('บึงกาฬ','Bung khla');
